---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit this file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse   = TRUE,
  warning    = FALSE,
  message    = FALSE,
  comment    = "#>",
  echo       = FALSE
)

library(tinytable)
```

This repo is for keeping track of package features as we build them out. The only file that needs to be updated is the [df.csv](https://github.com/surveydown-dev/todo/blob/main/df.csv) file. With each update, a GitHub action runs to re-build this README file with an updated table.

```{r}
# Read in the complete list
df <- read.csv("df.csv", check.names = FALSE)

# Separate dataframes by Progress value
feature_ids <- which(df$Progress == 1)
todo_ids <- which(df$Progress == 2)
feature_apps_ids <- which(df$Progress == 3)
todo_apps_ids <- which(df$Progress == 4)

# Remove Progress column
df$Progress <- NULL

# Create separate dataframes
feature_df <- df[feature_ids,]
todo_df <- df[todo_ids,]
feature_apps_df <- df[feature_apps_ids,]
todo_apps_df <- df[todo_apps_ids,]

# Order feature dataframes by Version
feature_df <- feature_df[order(feature_df$Version),]
feature_apps_df <- feature_apps_df[order(feature_apps_df$Version),]
```

### Features - surveydown

```{r}
feature_df |> 
  tt(theme = "grid") |>
  style_tt(fontsize = 0.9) |>
  style_tt(i = 0, align = "c") |>
  style_tt(j = c(1, 2, 3, 4), align = "c")
```

### To Do - surveydown

```{r}
todo_df |>
  tt(theme = "grid") |>
  style_tt(fontsize = 0.9) |>
  style_tt(i = 0, align = "c") |>
  style_tt(j = c(1, 2, 3, 4), align = "c")
```

### Features - sdApps

```{r}
feature_apps_df |> 
  tt(theme = "grid") |>
  style_tt(fontsize = 0.9) |>
  style_tt(i = 0, align = "c") |>
  style_tt(j = c(1, 2, 3, 4), align = "c")
```

### To Do - sdApps

```{r}
todo_apps_df |>
  tt(theme = "grid") |>
  style_tt(fontsize = 0.9) |>
  style_tt(i = 0, align = "c") |>
  style_tt(j = c(1, 2, 3, 4), align = "c")
```